# Generated by Django 3.0.3 on 2020-03-24 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20200324_1532'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
