# Generated by Django 3.0.3 on 2020-03-24 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notifications', '0003_delete_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.CharField(max_length=256)),
                ('timestamp', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'notifications',
                'managed': False,
            },
        ),
    ]
