# Generated by Django 3.0.3 on 2020-03-24 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'managed': True},
        ),
    ]
