# Generated by Django 3.0.3 on 2020-03-24 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_auto_20200324_1601'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'managed': False},
        ),
    ]
