# Generated by Django 3.0.3 on 2020-03-10 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('clip_id', models.AutoField(primary_key=True, serialize=False)),
                ('clip_url', models.CharField(max_length=256)),
                ('date_added', models.DateField()),
            ],
            options={
                'db_table': 'clips',
                'managed': False,
            },
        ),
    ]
