# Generated by Django 3.0.3 on 2020-03-10 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('camera_id', models.AutoField(primary_key=True, serialize=False)),
                ('device_type', models.IntegerField()),
                ('ip', models.CharField(max_length=24)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'camera',
                'managed': False,
            },
        ),
    ]
