# Generated by Django 3.0.2 on 2020-01-22 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=32)),
                ('lastname', models.CharField(max_length=32)),
                ('username', models.CharField(max_length=32)),
                ('encrypted_password', models.CharField(max_length=512)),
                ('email', models.CharField(max_length=64)),
            ],
        ),
    ]
