# Generated by Django 3.0.3 on 2020-02-18 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_camera_clip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('notficaton', models.CharField(max_length=256)),
                ('timestamp', models.CharField(max_length=256)),
            ],
        ),
    ]
