# Generated by Django 3.0.3 on 2020-02-18 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='notficaton',
            new_name='notificaton',
        ),
    ]
