# Generated by Django 3.0.3 on 2020-02-18 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200218_2038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='notificaton',
            new_name='notification',
        ),
    ]
